config/routes.rb
Rails.application.routes.draw do
  #THIS NEEDS TO BE ABOVE THE RESOURCES!!!
  get 'users/legal'
  get 'become_tutor', to: 'users#become_tutor', as: 'become_tutor'
  resources :subjects
  resources :tutor_subjects
  resources :families
  resources :accesses
  resources :tutor_client_relationships do
    post 'comments', to: 'comments#create'
  end
  resources :reviews

  devise_for :users, :path => 'u'
  resources :users, only: [:show, :new, :edit, :update, :create]
  #resources :users, only: [:index, :show, :new, :edit, :update, :create]
  #resources :users do
    #resources :recruiters #-> url.com/users/:user_id/recruiters
  #end

  get 'pages/about_us'
  get 'pages/contact'
  get 'pages/apiconnecting'
  get 'pages/room1'
  get 'pages/room2'
  get 'pages/room3'
  get 'pages/room4'
  get 'pages/room5'
  post 'request_contact', to: 'pages#request_contact'
  get 'pages/tutor_list'
  get 'pages/bootstrap_test'
  post 'tutor_booking', to: 'users#book_tutor', as: 'tutor_booking'
  post 'add_subject', to: 'users#add_subject', as: 'add_subject'
  get 'room', to: 'tutor_client_relationships#room'
  get 'delete_room', to: 'tutor_client_relationships#delete_room'
  root "pages#home"
end

app/models/tutor_client_relationship.rb
class TutorClientRelationship < ApplicationRecord

    has_many_attached :files, dependent: :destroy
    has_many :comments, dependent: :destroy
end

app/controllers/tutor_client_relationships_controller.rb
class TutorClientRelationshipsController < ApplicationController
  before_action :check_user, :set_tutor_client_relationship, only: %i[ show edit update destroy ]
  before_action :check_index, only: %i[ index ]

  def check_index
    if current_user == nil
      flash.alert = "Not allowed!"
      redirect_to root_path
    end
  end


  def check_user

    rel = TutorClientRelationship.find(params[:id])

    if current_user.role == 'tutor'
      if current_user.id == rel.clientID || current_user.id == rel.tutorID
        puts('allowed connection')
      elsif Family.where(parentID: current_user.id, childID: rel.clientID).present?
        puts('allowed connection')
      else
        flash.alert = "Not allowed!"
        redirect_to root_path
      end

    elsif current_user.role == 'adult'
      if current_user.id == rel.clientID
        puts('allowed connection')
      elsif Family.where(parentID: current_user.id, childID: rel.clientID).present?
        puts('allowed connection')
      else
        flash.alert = "Not allowed!"
        redirect_to root_path
      end

    elsif current_user.role == 'child'
      if current_user.id == rel.clientID
        puts('allowed connection')
      else
        flash.alert = "Not allowed!"
        redirect_to root_path
      end
    end
  end

  # GET /tutor_client_relationships or /tutor_client_relationships.json
  def index
    # ---Fetches all the tutors of the current user.
    @tutor_relationships = TutorClientRelationship.where(clientID: current_user.id)

    # ---Fetches all the clients of the current user.
    @client_relationships = TutorClientRelationship.where(tutorID: current_user.id)
    
    # ---Fetches all of the tutors of the current user's children.
    @children = Family.where(parentID: current_user.id)

    # Create array of just the children's IDs.
    @children_ids = []
    @children.each do |child|
      @children_ids.push(child.childID)
    end

    @children_tutor_relationships = TutorClientRelationship.where(clientID: [@children_ids])

  end

  # GET /tutor_client_relationships/1 or /tutor_client_relationships/1.json
  def show
    @tutor_client_relationship = TutorClientRelationship.find(params[:id])

    @client = client

    @comment = Comment.new
    @comments = @tutor_client_relationship.comments.order("created_at DESC")
  end

  

  # GET /tutor_client_relationships/new
  def new
    @tutor_client_relationship = TutorClientRelationship.new
  end

  # GET /tutor_client_relationships/1/edit
  def edit
  end

  # POST /tutor_client_relationships or /tutor_client_relationships.json
  def create
    @tutor_client_relationship = TutorClientRelationship.new(tutor_client_relationship_params)

    respond_to do |format|
      if @tutor_client_relationship.save
        format.html { redirect_to @tutor_client_relationship, notice: "Tutor client relationship was successfully created." }
        format.json { render :show, status: :created, location: @tutor_client_relationship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutor_client_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutor_client_relationships/1 or /tutor_client_relationships/1.json
  def update
    respond_to do |format|
      if @tutor_client_relationship.update(tutor_client_relationship_params)
        format.html { redirect_to @tutor_client_relationship, notice: "Tutor client relationship was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor_client_relationship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutor_client_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutor_client_relationships/1 or /tutor_client_relationships/1.json
  def destroy
    @tutor_client_relationship.destroy
    respond_to do |format|
      format.html { redirect_to tutor_client_relationships_url, notice: "Tutor client relationship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def create_room
    response = client.create_new_room(params[:id])
    
    # client.delete_room(JSON.parse(response.body)['name'])
  end

  def room
    puts '*****************'
    puts client.check_room(params[:id]).code
    puts current_user.role

    if client.check_room(params[:id]).code != '200' && current_user.role == 'tutor'
      create_room()
      flash.alert = 'Room Created!'
      redirect_to tutor_client_relationship_path(params[:id])
    elsif client.check_room(params[:id]).code != '200' && (current_user.role == 'adult' || current_user.role == 'child')
      flash.alert = 'Session has already finished!'
      redirect_to tutor_client_relationship_path(params[:id])
    end

    @room_link = 'https://woo-test.daily.co/' + params[:id]
  end

  def delete_room
    puts params
    client.delete_room(params[:id])
    flash.alert = 'Room Destroyed!'
    redirect_to tutor_client_relationship_path(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor_client_relationship
      @tutor_client_relationship = TutorClientRelationship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutor_client_relationship_params
      params.require(:tutor_client_relationship).permit(:relID, :tutorID, :clientID, files: [])
    end
  
end

app/helpers/tutor_client_relationships_helper.rb
module TutorClientRelationshipsHelper
end

app/views/tutor_client_relationships/edit.html.erb
<%= form_with(model: @tutor_client_relationship) do |form| %>

  <div>
    <%= form.file_field :files, multiple: true %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutor_client_relationships/index.html.erb
<!--  This is the page that shows all of the subjects and tutors the currently logged in user is signed up to
      It is also the point of contact between students and tutors.
      If a tutor is signed in this page shows him the students that have signed up to him/her -->


<!-- The following is how the hub looks when there is a student signed in. In that case it is called a Learning Center-->
<h1>Personal Learning Center</h1>
<p>Access your personal tutor's hubs.</p>

<% if @tutor_relationships.first == nil %>
    <p> You haven't signed up to any tutors yet!</p>
<%else%>
    <table>
        <tr>
            <th> Subject </th>
            <th> Tutor </th>
        </tr>
        <% @tutor_relationships.all.each do |tutorclient| %>
            <tr>
                <td><%= Subject.where(subjectID: tutorclient.subjectID).first.name %> </td>
                <td><%= User.where(id: tutorclient.tutorID).first.forename%> <%= User.where(id: tutorclient.tutorID).first.surname%></td>
                <td> <%= link_to "Go To Hub", tutor_client_relationship_path(tutorclient.id) %> </td>

                <% if current_user.role == 'tutor' || current_user.role == 'adult'%>
                    <td><%= link_to "Delete",tutor_client_relationship_path(tutorclient.id), method: :delete %></td>
                <% end %>
            </tr>
        <% end %>
    </table>
<% end %>

<br>
<br>
<br>

<!-- The following is how the hub looks when there is a tutor signed in. In that case it is called a Teaching Center-->
<% if current_user.role == 'tutor' %>
    <h1>Teaching Center</h1>
    <p>Access your student's hubs.</p>

    <% if @client_relationships.first == nil %>
        <p> You don't have any students yet!</p>
    <%else%>
        <table>
            <tr>
                <th> Subject </th>
                <th> Student </th>
            </tr>
            <% @client_relationships.all.each do |tutorclient| %>
                <tr>
                    <td><%= Subject.where(subjectID: tutorclient.subjectID).first.name %> </td>
                    <td><%= User.where(id: tutorclient.clientID).first.forename%> <%= User.where(id: tutorclient.clientID).first.surname%></td>
                    <td> <%= link_to "Go To Hub", tutor_client_relationship_path(tutorclient.id) %> </td>
                    <td><%= link_to "Delete",tutor_client_relationship_path(tutorclient.id), method: :delete %></td>
                </tr>
            <% end %>
        </table>
    <% end %>
<% end %>
        
    
<br>
<br>
<br>

<!-- The following is how the hub looks when there is a parent signed in. In that case it is called a Parental Control Page-->
<% if Family.where(parentID: current_user.id).first != nil %>

    <h1>Parental Access</h1>
    <p>Access your children's personal hubs.</p>

    <% if @children_tutor_relationships.first == nil %>
        <p> Your children have no tutors yet!</p>
    <%else%>
        <table>
            <tr>
                <th> Child's Name </th>
                <th> Subject </th>
                <th> Tutor </th>
            </tr>
            <% @children_tutor_relationships.all.each do |tutorclient| %>
                <tr>
                    <td><%= User.where(id: tutorclient.clientID).first.forename %> </td>
                    <td><%= Subject.where(subjectID: tutorclient.subjectID).first.name %> </td>
                    <td><%= User.where(id: tutorclient.tutorID).first.forename%> <%= User.where(id: tutorclient.tutorID).first.surname%></td>
                    <td> <%= link_to "Go To Hub", tutor_client_relationship_path(tutorclient.id) %> </td>
                    <td><%= link_to "Delete",tutor_client_relationship_path(tutorclient.id), method: :delete %></td>
                </tr>
            <% end %>
        </table>       
    <%end%>
    
<% end %>

app/views/tutor_client_relationships/room.html.erb
<script crossorigin src="https://unpkg.com/@daily-co/daily-js"></script>
<script>
  callFrame = window.DailyIframe.createFrame({
    showLeaveButton: true,
    iframeStyle: {
      position: 'fixed',
      width: '80%',
     height: '80%'
    }
  });
  callFrame.join({ url: "<%= @room_link %>"})
</script>

app/views/tutor_client_relationships/show.html.erb
<h1> Your Hub Area </h1>

<p1> Current Tutor: </p1>
<%= User.where(id: @tutor_client_relationship.tutorID).first.full_name %>
<br>
<p1> Current Client: </p1>
<%= User.where(id: @tutor_client_relationship.clientID).first.full_name %>

<br>
<br>
<br>

<h4> Your File Sharing: </h4>
<ul>
    <% @tutor_client_relationship.files.each do |file| %>
        <li>
            <%= file.filename%>
            <%= link_to 'View file', file %>
            <%= link_to 'Download file', file, download: '' %>
        </li>
    <% end %>
</ul>

<%= link_to 'Add new file', edit_tutor_client_relationship_path %>


<br>
<br>
<br>

<h4> Sessions </h4>

<% if @client.check_room(String(@tutor_client_relationship.id)).code == '200' %>
    <%= link_to 'Join Session', room_path(:id => @tutor_client_relationship.id), target: '_blank' %>
    
    <% if current_user.role == 'tutor' %>
        <br>
        <%= link_to 'Delete Session', delete_room_path(:id => @tutor_client_relationship.id) %>
    <%end%>
<% else %>
    <% if current_user.role == 'tutor' %>
        <%= link_to 'Start Session', room_path(:id => @tutor_client_relationship.id, target: '_blank')%>
    <% else%>
        <p>No active sessions!</p>
    <% end %>

<% end %>

<br>
<br>

<%= form_with model: [@tutor_client_relationship, @comment], local: true do |f| %>
	<%= f.text_field :body %>
	<%= f.submit "comment" %>
<% end %>

<% @comments.each do |comment| %>
	[<%= comment.created_at.strftime("%I:%M %p") %>] <%= comment.user.forename %> <%= comment.user.surname %>: <%= comment.body %>
	<br />
<% end %>