config/routes.rb
Rails.application.routes.draw do
  #THIS NEEDS TO BE ABOVE THE RESOURCES!!!
  get 'users/legal'
  get 'become_tutor', to: 'users#become_tutor', as: 'become_tutor'
  resources :subjects
  resources :tutor_subjects
  resources :families
  resources :accesses
  resources :tutor_client_relationships do
    post 'comments', to: 'comments#create'
  end
  resources :reviews

  devise_for :users, :path => 'u'
  resources :users, only: [:show, :new, :edit, :update, :create]
  #resources :users, only: [:index, :show, :new, :edit, :update, :create]
  #resources :users do
    #resources :recruiters #-> url.com/users/:user_id/recruiters
  #end

  get 'pages/about_us'
  get 'pages/contact'
  get 'pages/apiconnecting'
  get 'pages/room1'
  get 'pages/room2'
  get 'pages/room3'
  get 'pages/room4'
  get 'pages/room5'
  post 'request_contact', to: 'pages#request_contact'
  get 'pages/tutor_list'
  get 'pages/bootstrap_test'
  post 'tutor_booking', to: 'users#book_tutor', as: 'tutor_booking'
  post 'add_subject', to: 'users#add_subject', as: 'add_subject'
  get 'room', to: 'tutor_client_relationships#room'
  get 'delete_room', to: 'tutor_client_relationships#delete_room'
  root "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  validates :forename, :surname, presence: true
  enum role: [:adult, :child, :tutor]

  after_initialize do
  	if self.new_record?
  		self.role ||= :adult
  	end
  end

  def full_name
    "#{forename} #{surname}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def show
	  	@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = current_user
	end

	def update
		puts '*******'
		puts params
		puts update_user_params
		respond_to do |format|
			if current_user.update(update_user_params)
				format.html { redirect_to current_user, notice: 'You successfully updated your profile' }
			else
				format.html { render :edit }
			end
		end
	end

	def legal
	end

	def become_tutor
		@user = current_user
		@user.role = 'tutor'
		if @user.save
			redirect_to user_path(@user), notice: "User successfully updated"
		else
			redirect_to user_path(@user), alert: "Failed to update user"
		end
	end

	def create
		@user = User.new(new_user_params)
		@user.role = 'child'
		if @user.save
			Family.new(parentID: current_user.id, childID: @user.id).save
			redirect_to user_path(@user), notice: "User successfully created"
		else
			render :new
		end
	end

	#helper method to display tutor's subjects on their profile pages
	def subj
		@tutor_subjects = TutorSubject.where(tutorID: @user.id).select(:subjectID)
		@tutor_subjects = Subject.where(subjectID: @tutor_subjects)
		subs = []
		@tutor_subjects.each do |tutor_subject|
			subs.append([tutor_subject.name, tutor_subject.subjectID])
		end
	return subs
	end

	def book_tutor
		tutorID = params[:tutorID]
		clientID = params[:clientID]
		subjectID = params[:subjectID]

		maxkey = TutorClientRelationship.maximum("relID")
		if maxkey.nil?
			maxkey = 0
		end
		maxkey = maxkey + 1

		relationship = TutorClientRelationship.new(tutorID: tutorID, clientID: clientID, subjectID: subjectID, relID: maxkey)

		conflicts = TutorClientRelationship.where(subjectID: subjectID, clientID: clientID)

		if conflicts.length > 0
			redirect_to user_path(tutorID), alert: "Booking failed: You're already booked to this subject"
			return
		end

		if relationship.valid?
			relationship.save!
			access = Access.new(relID: maxkey)
			access.save!
			redirect_to tutor_client_relationships_path, notice: 'Booking saved successfully'
		else
			redirect_to user_path(tutorID), alert: 'Booking failed: Invalid arguments'
		end
	end

	def get_reviews
		reviews = Review.where(tutorID: @user.id)
		review_arr = []

		reviews.each do |review|
			content = []
			user = User.where(id: review.userID).first
			username = "Anon"
			unless user.nil?
				username = user.forename
			end
			content.append(username)
			content.append(review.rating)
			content.append(review.content)
			review_arr.append(content)
		end

		return review_arr
	end

	def average_reviews
		reviews = get_reviews
		total = 0.0
		num_of_reviews = reviews.length

		reviews.each do |review|
			total += review[1]
		end

		total / num_of_reviews
	end

	def add_subject
		sub_name = params[:subject_name]
		if sub_name.empty?
			redirect_to user_path(current_user.id), alert: "Text field must be filled"
			return
		end
		matches = Subject.where(name: sub_name)

		maxkey = TutorSubject.maximum("relID")
		relkey = maxkey+1
		subkey = 0
		if matches.length > 0
			subkey = matches[0].subjectID
		else
			maxsubkey = Subject.maximum("subjectID")
			new_sub = Subject.new(subjectID: maxsubkey+1, name: sub_name)
			subkey = maxsubkey+1
			unless new_sub.save
				redirect_to user_path(current_user.id), notice: "New subject could not be made"
				return
			end
		end

		new_ts = TutorSubject.new(relID: relkey, tutorID: current_user.id, subjectID: subkey)
		if new_ts.save
			redirect_to user_path(current_user.id), notice: "New subject created"
		else
			redirect_to user_path(current_user.id), alert: "Subject relationship failed to save"
		end
	end

	helper_method :subj, :get_reviews, :average_reviews

	private

	def user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:phone,
			:dob
		)

		params.except(:booking).permit(
		:tutorID,
		:clientID,
		:subjectID
		)

		params.except(:sub).permit(
			:subject_name
		)
	end

	def new_user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:email,
			:dob,
			:password,
			:password_confirmation,
		)
	end


	def update_user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:phone,
			:dob,
			:bio
		)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
	<% if user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
				<% user.errors.full_messages.each do |message| %>
					<li><%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<%= form.label :forename %>
		<%= form.text_field :forename %>
	</div>

	<div>
		<%= form.label :surname %>
		<%= form.text_field :surname %>
	</div>

	<div>
		<%= form.label :phone %>
		<%= form.text_field :phone %>
	</div>

	<div>
		<%= form.label :dob %>
		<%= form.date_field :dob %>
	</div>

	<div>
		<%= form.label :bio %>
		<%= form.text_area :bio %>
	</div>

	<div>
		<%= form.submit %>
		<%= link_to 'Cancel', users_path %>
	</div>
<% end %>

app/views/users/_new_form.erb
<%= form_for(@user) do |f| %>
  <fieldset>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :forename %><br />
      <%= f.text_field :forename, autofocus: true, autocomplete: "Forename" %>
    </div>

    <div class="field">
      <%= f.label :surname %><br />
      <%= f.text_field :surname, autofocus: true, autocomplete: "Surname" %>
    </div>

    <div class="field">
      <%= f.label :dob, "Date of Birth" %><br />
      <%= f.date_field :dob, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password, "Password (6 or more characters)" %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
  </fieldset>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.full_name, user %>
</li>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>List of all Users</h1>

<ul>
	<%= render @users %>
</ul>

app/views/users/legal.html.erb
<h1> Legal Permission </h1>
<br>
<p> In line with GDPR standards, we would like your consent with our handling of your child's data. </p>
<p> For our application to run, we will need to store personal information on your child account such as their Name, Date of Birth and Comment history. </p>
<br>
<br>
<br>

<%= link_to "Decline", user_path(current_user) %>
<%= link_to 'Accept', new_user_path %>

app/views/users/new.html.erb
<h1>Create your Child's account</h1>

<%= render 'new_form' %>

app/views/users/show.html.erb
<h1><% @user.full_name %></h1>

<% if current_user.id == @user.id %>
  <p><strong><u>Public Profile</u></strong></p>
<% end %>

<p><strong><%= @user.full_name %></strong></p>
<p><strong>Role:</strong> <%= @user.role %></p>
<p><strong>Bio:</strong> <%= @user.bio %></p>



<!--Code gets a 2d array of subject names and their ids and displays a button for each one.
The button then passes the current user id, tutor id and subject id to a method in the user controller
which creates a relationship of the tutor and client along with the chosen subject.
Finally a access entry is created which holds the relationship id and a nil value for the room link
-->
<% if @user.role == 'tutor' && current_user.id != @user.id %>
	<p> To get in contact with a tutor, please book one of the subjects they offer below. </p>
	<p> Please note that you can only book one tutor for each subject <p>
	<p><strong>Subjects:</strong><p>
	<%
    subjects = subj
    subjects.each { |subject|%>
    <%unless subject[0].nil? %>
      <%=button_to subject[0], tutor_booking_path(tutorID: @user.id, clientID: current_user.id, subjectID: subject[1]), method: :post%>
    <%end }%>
  <%session[:tutorID] = @user.id %>
  <%= button_to "Review Tutor", new_review_path(tutorID: @user.id), method: :get%>
  <% reviews = get_reviews %>
  <p>Average Rating: <%= average_reviews %></p>
  <p> Reviews </p>
  <% reviews.each { |review| %>
    <div class="card">
      <p><%=review[0] %></p>
      <p><%="Rating: " + review[1].to_s %></p>
      <p><%=review[2] %></p>
    </div>
  <% }
  %>
  <% end %>


<% if current_user.id == @user.id %>
	<p><strong><u>Private Info</u></strong></p>
	<p><strong>Phone:</strong> <%= @user.phone %></p>
	<p><strong>D.O.B:</strong> <%= @user.dob %></p>
	<%= link_to 'Edit My Profile', edit_user_path(current_user) %>
	<% if current_user.role == 'adult' || current_user.role == 'tutor' %>
		<%= link_to 'Create Child Account', users_legal_path %>
	<% end %>
	<% if current_user.role == 'adult' %>
		<%= link_to 'Become Tutor', become_tutor_path %>
	<% end %>
  <% if current_user.role == 'tutor' %>
    <%= form_with url: add_subject_path, method: :post do |form| %>
      <%= form.label :subject_name, "New Subject:" %>
      <%= form.text_field :subject_name%>
      <%= form.submit "Add"%>
    <% end %>
  <% end %>
<% end %>