config/routes.rb
Rails.application.routes.draw do
  #THIS NEEDS TO BE ABOVE THE RESOURCES!!!
  get 'users/legal'
  get 'become_tutor', to: 'users#become_tutor', as: 'become_tutor'
  resources :subjects
  resources :tutor_subjects
  resources :families
  resources :accesses
  resources :tutor_client_relationships do
    post 'comments', to: 'comments#create'
  end
  resources :reviews

  devise_for :users, :path => 'u'
  resources :users, only: [:show, :new, :edit, :update, :create]
  #resources :users, only: [:index, :show, :new, :edit, :update, :create]
  #resources :users do
    #resources :recruiters #-> url.com/users/:user_id/recruiters
  #end

  get 'pages/about_us'
  get 'pages/contact'
  get 'pages/apiconnecting'
  get 'pages/room1'
  get 'pages/room2'
  get 'pages/room3'
  get 'pages/room4'
  get 'pages/room5'
  post 'request_contact', to: 'pages#request_contact'
  get 'pages/tutor_list'
  get 'pages/bootstrap_test'
  post 'tutor_booking', to: 'users#book_tutor', as: 'tutor_booking'
  post 'add_subject', to: 'users#add_subject', as: 'add_subject'
  get 'room', to: 'tutor_client_relationships#room'
  get 'delete_room', to: 'tutor_client_relationships#delete_room'
  root "pages#home"
end

app/models/access.rb
class Access < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tutor_client_relationship
  validates :body, presence: true, allow_blank: false
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/tutor_subject.rb
class TutorSubject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  validates :forename, :surname, presence: true
  enum role: [:adult, :child, :tutor]

  after_initialize do
  	if self.new_record?
  		self.role ||= :adult
  	end
  end

  def full_name
    "#{forename} #{surname}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      # Send an email
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

	def show
	  	@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = current_user
	end

	def update
		puts '*******'
		puts params
		puts update_user_params
		respond_to do |format|
			if current_user.update(update_user_params)
				format.html { redirect_to current_user, notice: 'You successfully updated your profile' }
			else
				format.html { render :edit }
			end
		end
	end

	def legal
	end

	def become_tutor
		@user = current_user
		@user.role = 'tutor'
		if @user.save
			redirect_to user_path(@user), notice: "User successfully updated"
		else
			redirect_to user_path(@user), alert: "Failed to update user"
		end
	end

	def create
		@user = User.new(new_user_params)
		@user.role = 'child'
		if @user.save
			Family.new(parentID: current_user.id, childID: @user.id).save
			redirect_to user_path(@user), notice: "User successfully created"
		else
			render :new
		end
	end

	#helper method to display tutor's subjects on their profile pages
	def subj
		@tutor_subjects = TutorSubject.where(tutorID: @user.id).select(:subjectID)
		@tutor_subjects = Subject.where(subjectID: @tutor_subjects)
		subs = []
		@tutor_subjects.each do |tutor_subject|
			subs.append([tutor_subject.name, tutor_subject.subjectID])
		end
	return subs
	end

	def book_tutor
		tutorID = params[:tutorID]
		clientID = params[:clientID]
		subjectID = params[:subjectID]

		maxkey = TutorClientRelationship.maximum("relID")
		if maxkey.nil?
			maxkey = 0
		end
		maxkey = maxkey + 1

		relationship = TutorClientRelationship.new(tutorID: tutorID, clientID: clientID, subjectID: subjectID, relID: maxkey)

		conflicts = TutorClientRelationship.where(subjectID: subjectID, clientID: clientID)

		if conflicts.length > 0
			redirect_to user_path(tutorID), alert: "Booking failed: You're already booked to this subject"
			return
		end

		if relationship.valid?
			relationship.save!
			access = Access.new(relID: maxkey)
			access.save!
			redirect_to tutor_client_relationships_path, notice: 'Booking saved successfully'
		else
			redirect_to user_path(tutorID), alert: 'Booking failed: Invalid arguments'
		end
	end

	def get_reviews
		reviews = Review.where(tutorID: @user.id)
		review_arr = []

		reviews.each do |review|
			content = []
			user = User.where(id: review.userID).first
			username = "Anon"
			unless user.nil?
				username = user.forename
			end
			content.append(username)
			content.append(review.rating)
			content.append(review.content)
			review_arr.append(content)
		end

		return review_arr
	end

	def average_reviews
		reviews = get_reviews
		total = 0.0
		num_of_reviews = reviews.length

		reviews.each do |review|
			total += review[1]
		end

		total / num_of_reviews
	end

	def add_subject
		sub_name = params[:subject_name]
		if sub_name.empty?
			redirect_to user_path(current_user.id), alert: "Text field must be filled"
			return
		end
		matches = Subject.where(name: sub_name)

		maxkey = TutorSubject.maximum("relID")
		relkey = maxkey+1
		subkey = 0
		if matches.length > 0
			subkey = matches[0].subjectID
		else
			maxsubkey = Subject.maximum("subjectID")
			new_sub = Subject.new(subjectID: maxsubkey+1, name: sub_name)
			subkey = maxsubkey+1
			unless new_sub.save
				redirect_to user_path(current_user.id), notice: "New subject could not be made"
				return
			end
		end

		new_ts = TutorSubject.new(relID: relkey, tutorID: current_user.id, subjectID: subkey)
		if new_ts.save
			redirect_to user_path(current_user.id), notice: "New subject created"
		else
			redirect_to user_path(current_user.id), alert: "Subject relationship failed to save"
		end
	end

	helper_method :subj, :get_reviews, :average_reviews

	private

	def user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:phone,
			:dob
		)

		params.except(:booking).permit(
		:tutorID,
		:clientID,
		:subjectID
		)

		params.except(:sub).permit(
			:subject_name
		)
	end

	def new_user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:email,
			:dob,
			:password,
			:password_confirmation,
		)
	end


	def update_user_params
		params.require(:user).permit(
			:forename,
			:surname,
			:phone,
			:dob,
			:bio
		)
	end

end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tutor_list_helper.rb
module TutorListHelper
end

app/helpers/tutor_subjects_helper.rb
module TutorSubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Woo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' % > %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.jpg') %>
  </head>

  <body>
    
    <header>
      <%= render 'shared/header' %>
    </header>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"> <%= image_tag('woo.jpg', :size => "115x50") %> </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link nav-hover" %>
            </li>

            <li class="nav-item">
                <%= link_to "About Us", pages_about_us_path, class: "nav-link nav-hover" %>
            </li>

            <li class="nav-item">
                <%= link_to "Contact Us", pages_contact_path, class: "nav-link nav-hover" %>
            </li>

            <li class="nav-item">
                <%= link_to "All Tutors", pages_tutor_list_path, class: "nav-link nav-hover" %>
            </li>
            

            <% if user_signed_in? %>

              <% if current_user.role == 'tutor' %>
                <li class="nav-item">
                  <%= link_to "Teaching Center", tutor_client_relationships_path, class: "nav-link nav-hover" %>
                </li>
              <% end %>

              <% if current_user.role == 'child' %>
                <li class="nav-item">
                  <%= link_to "Learning Center", tutor_client_relationships_path, class: "nav-link nav-hover" %>
                </li>
              <% end %>

              <% if current_user.role == 'adult' %>
                <% if Family.where(parentID: current_user.id).first != nil %>
                  <li class="nav-item">
                    <%= link_to "Parental Control Page", tutor_client_relationships_path, class: "nav-link nav-hover" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "Learning Center", tutor_client_relationships_path, class: "nav-link nav-hover" %>
                  </li>
                <% end %>
              <% end %>


                <li class="nav-item">
                    <%= link_to "Profile", user_path(current_user), class: "nav-link nav-hover" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, class: "nav-link nav-hover" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Public Rooms", pages_apiconnecting_path, class: "nav-link nav-hover" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: "nav-link nav-hover" %>
                </li>

                <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class: "nav-link nav-hover" %>
                </li>
            <% end %>

            <li class="nav-item">
                <p class= "font-weight-bolder nav-link nav-hover">
                  <!-- get_user_logged_in is a method that has been defined in the application controller. It returns the user that is currently signed in and it shows up on each page -->
                  <%= get_user_logged_in  %>
                </p>
            </li>
    </ul>
  </div>
</nav>

<!--<div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div> -->

<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>