config/routes.rb
Rails.application.routes.draw do
  #THIS NEEDS TO BE ABOVE THE RESOURCES!!!
  get 'users/legal'
  get 'become_tutor', to: 'users#become_tutor', as: 'become_tutor'
  resources :subjects
  resources :tutor_subjects
  resources :families
  resources :accesses
  resources :tutor_client_relationships do
    post 'comments', to: 'comments#create'
  end
  resources :reviews

  devise_for :users, :path => 'u'
  resources :users, only: [:show, :new, :edit, :update, :create]
  #resources :users, only: [:index, :show, :new, :edit, :update, :create]
  #resources :users do
    #resources :recruiters #-> url.com/users/:user_id/recruiters
  #end

  get 'pages/about_us'
  get 'pages/contact'
  get 'pages/apiconnecting'
  get 'pages/room1'
  get 'pages/room2'
  get 'pages/room3'
  get 'pages/room4'
  get 'pages/room5'
  post 'request_contact', to: 'pages#request_contact'
  get 'pages/tutor_list'
  get 'pages/bootstrap_test'
  post 'tutor_booking', to: 'users#book_tutor', as: 'tutor_booking'
  post 'add_subject', to: 'users#add_subject', as: 'add_subject'
  get 'room', to: 'tutor_client_relationships#room'
  get 'delete_room', to: 'tutor_client_relationships#delete_room'
  root "pages#home"
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_access, only: %i[ show edit update destroy ]

  # GET /accesses or /accesses.json
  def index
    @accesses = Access.all
  end

  # GET /accesses/1 or /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
  end

  # POST /accesses or /accesses.json
  def create
    @access = Access.new(access_params)

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: "Access was successfully created." }
        format.json { render :show, status: :created, location: @access }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accesses/1 or /accesses/1.json
  def update
    respond_to do |format|
      if @access.update(access_params)
        format.html { redirect_to @access, notice: "Access was successfully updated." }
        format.json { render :show, status: :ok, location: @access }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1 or /accesses/1.json
  def destroy
    @access.destroy
    respond_to do |format|
      format.html { redirect_to accesses_url, notice: "Access was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access
      @access = Access.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def access_params
      params.require(:access).permit(:relID, :videolink)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_form.html.erb
<%= form_with(model: access) do |form| %>
  <% if access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
        <% access.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relID %>
    <%= form.number_field :relID %>
  </div>

  <div class="field">
    <%= form.label :videolink %>
    <%= form.text_field :videolink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<h1>Editing Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Show', @access %> |
<%= link_to 'Back', accesses_path %>

app/views/accesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accesses</h1>

<table>
  <thead>
    <tr>
      <th>Relid</th>
      <th>Videolink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accesses.each do |access| %>
      <tr>
        <td><%= access.relID %></td>
        <td><%= access.videolink %></td>
        <td><%= link_to 'Show', access %></td>
        <td><%= link_to 'Edit', edit_access_path(access) %></td>
        <td><%= link_to 'Destroy', access, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access', new_access_path %>

app/views/accesses/new.html.erb
<h1>New Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Back', accesses_path %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relid:</strong>
  <%= @access.relID %>
</p>

<p>
  <strong>Videolink:</strong>
  <%= @access.videolink %>
</p>

<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>